### ISSUE TITLE
Removing unnecessary properties in the dbpedia querying

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/RDF-Py-Examples#3]
To remove unnecessary properties that are ok in DBPedia but we do not need them at all. For example, the followings:
`@prefix ns1: <http://dbpedia.org/ontology/>.`
`@prefix ns4: <http://purl.org/voc/vrank#> .`
- `ns1:thumbnail`
- `ns1:wikiPageID` 
- `ns1:wikiPageRevisionID`
- `ns4:hasRank`
- `foaf:depiction`

**Comment by mmaltsev** [comment]
Exclusion of the properties listed above added to the logic of updating the ontology. Most probably there should be more work on excluding useless properties.

**Comment by igrangel** [comment]
Could you please link it to the line of code where this is done?

**Comment by mmaltsev** [comment]
The variable that stores properties to exclude can be found [here](https://github.com/igrangel/RDF-Py-Examples/blob/dece0eaa16d97ef473d1cd227e1bab65eacfcf0e/query_all_p3.py#L21).

**Comment by igrangel** [comment]
Excluding more properties from the dbpedia ontology - [here](https://github.com/i40-Tools/RDF-Py-Examples/blob/bcf0b1f1347f9d110e080a02fd96dba0e6306db4/query_all_p3.py#L25). 
We will close this issue for now. It might reopen or consulted later on.
